spring.application.name=tent-house-management

spring.datasource.url=jdbc:mysql://localhost:3306/tent_house_db
spring.datasource.username=root
spring.datasource.password=tent@123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

